#server config
  server:
    port: 8008

#datasource config
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://220.78.127.194:3306/dduckleaf
      username: team2member
      password: team2
      hikari:
        auto-commit: false

    # file upload
    servlet:
      multipart:
        # 파일 업로드 가능 여부 선택
        enabled: true
        # 업로드된 파일의 임시 저장 경로
        location: C:\dev
        # 한 번에 최대 업로드 가능 용량
        max-request-size: 100MB
        # 파일 하나의 최대 크기
        max-file-size: 20MB
#jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true
        ddl-auto: validate

##Live Reload 기능 활성화
#  devtools:
#    livereload:
#      enabled: true

  web:
    resources:
      static-locations: file:src/main/resources/static/

#  thymeleaf:
#    cache: false
#    prefix: file:src/main/resources/templates/

## SMTP config
  mail:
    host: smtp.gmail.com
    port: 587
    username: tkdjawlwhs@gmail.com
    password: a33196417
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  file:
    path: C:\final-project\dduckleaf\src\main\resources\static